name: Python CI

on:
  push:
    branches:
      - main  # or use the name of the branch you're working on
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest  # You can change this to another OS (e.g., windows-latest) if needed

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'  # Choose the Python version you want to use

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Make sure you have a requirements.txt for dependencies

    - name: Run tests (or your script)
      run: |
        python your_script.py  # Replace this with the script you want to run

